# Generated by Django 5.0.1 on 2026-01-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='library_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique Library ID', max_length=20, null=True, unique=True),
        ),
    ]
