# Generated by Django 5.0.1 on 2026-01-31 05:35

from django.db import migrations


def populate_library_ids(apps, schema_editor):
    Library = apps.get_model('libraries', 'Library')
    for index, library in enumerate(Library.objects.all(), start=1):
        if not library.library_id:
            library.library_id = f'LIB{index:06d}'
            library.save()


def reverse_populate(apps, schema_editor):
    pass  # No need to reverse


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_library_library_id'),
    ]

    operations = [
        migrations.RunPython(populate_library_ids, reverse_populate),
    ]
