# Generated by Django 5.0.1 on 2026-01-31 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('id_proof', models.FileField(upload_to='students/id_proofs/')),
                ('time_slot', models.CharField(choices=[('MORNING', 'Morning (6 AM - 12 PM)'), ('AFTERNOON', 'Afternoon (12 PM - 6 PM)'), ('EVENING', 'Evening (6 PM - 12 AM)'), ('FULL_DAY', 'Full Day')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='libraries.library')),
                ('seat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='seats.seat')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
    ]
