# Generated by Django 5.0.1 on 2026-01-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, help_text='Full address', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='education_level',
            field=models.CharField(blank=True, choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('COMPETITIVE_EXAM', 'Competitive Exam'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='institution_name',
            field=models.CharField(blank=True, help_text='School/College name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='preparing_for',
            field=models.CharField(blank=True, help_text='What exam/course they are preparing for', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(blank=True, help_text='Current qualification or class', max_length=200, null=True),
        ),
    ]
