# Generated by Django 5.0.1 on 2026-01-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_address_student_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='students/id_proofs/'),
        ),
    ]
