# Generated by Django 5.0.1 on 2026-01-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_date_of_birth_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, help_text='Student login password', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique Student ID', max_length=20, null=True, unique=True),
        ),
    ]
