# Generated by Django 5.0.1 on 2026-01-31 05:35

from django.db import migrations
from django.contrib.auth.hashers import make_password


def populate_student_ids_and_passwords(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Library = apps.get_model('libraries', 'Library')
    
    for library in Library.objects.all():
        students = Student.objects.filter(library=library)
        for index, student in enumerate(students, start=1):
            if not student.student_id:
                library_prefix = library.library_id.replace('LIB', 'STU') if library.library_id else 'STU000000'
                student.student_id = f'{library_prefix}-{index:04d}'
            
            # Set default password if not exists (phone number as default)
            if not student.password:
                default_password = student.phone[-4:] if len(student.phone) >= 4 else '1234'
                student.password = make_password(default_password)
            
            student.save()


def reverse_populate(apps, schema_editor):
    pass  # No need to reverse


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_password_student_student_id'),
        ('libraries', '0003_populate_library_ids'),
    ]

    operations = [
        migrations.RunPython(populate_student_ids_and_passwords, reverse_populate),
    ]
