# Generated by Django 5.0.1 on 2026-01-31 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_populate_library_ids'),
        ('students', '0006_populate_student_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('STUDY', 'Study & Learning'), ('SUCCESS', 'Success'), ('PERSEVERANCE', 'Perseverance'), ('MOTIVATION', 'Motivation'), ('INSPIRATION', 'Inspiration')], default='MOTIVATION', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Motivational Quote',
                'verbose_name_plural': 'Motivational Quotes',
                'db_table': 'motivational_quotes',
                'ordering': ['?'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('MATH', 'Mathematics'), ('SCIENCE', 'Science'), ('HISTORY', 'History'), ('LANGUAGE', 'Language'), ('EXAM_PREP', 'Exam Preparation'), ('REVISION', 'Revision'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags')),
                ('is_favorite', models.BooleanField(default=False)),
                ('color', models.CharField(choices=[('#FFFFFF', 'White'), ('#FEF3C7', 'Yellow'), ('#DBEAFE', 'Blue'), ('#D1FAE5', 'Green'), ('#FCE7F3', 'Pink'), ('#E0E7FF', 'Indigo'), ('#FED7AA', 'Orange')], default='#FFFFFF', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.student')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'student_notes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('DAILY', 'Daily Goal'), ('WEEKLY', 'Weekly Goal'), ('MONTHLY', 'Monthly Goal')], max_length=20)),
                ('target_hours', models.IntegerField(help_text='Target study hours')),
                ('current_hours', models.IntegerField(default=0, help_text='Current progress in hours')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_goals', to='students.student')),
            ],
            options={
                'verbose_name': 'Study Goal',
                'verbose_name_plural': 'Study Goals',
                'db_table': 'study_goals',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('session_type', models.CharField(choices=[('POMODORO', 'Pomodoro (25 min)'), ('CUSTOM', 'Custom Duration'), ('BREAK', 'Break Time')], default='CUSTOM', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Session notes or summary')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='students.student')),
            ],
            options={
                'verbose_name': 'Study Session',
                'verbose_name_plural': 'Study Sessions',
                'db_table': 'study_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='students.student')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'student_tasks',
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.CharField(max_length=100, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='libraries.library')),
            ],
            options={
                'verbose_name': 'Attendance QR Code',
                'verbose_name_plural': 'Attendance QR Codes',
                'db_table': 'attendance_qr_codes',
                'ordering': ['-date'],
                'unique_together': {('library', 'date')},
            },
        ),
    ]
