# Generated by Django 5.0.1 on 2026-02-02 05:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_deleted_at_student_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
