# Generated by Django 5.0.1 on 2026-02-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='ID of the user or student')),
                ('user_email', models.EmailField(help_text='Email of the user', max_length=254)),
                ('user_role', models.CharField(help_text='Role: STUDENT, LIBRARY, etc.', max_length=20)),
                ('analysis_type', models.CharField(choices=[('PERFORMANCE', 'Performance Analysis'), ('STUDY_PLAN', 'Study Plan'), ('NOTE_SUMMARY', 'Note Summary'), ('BUSINESS_INSIGHT', 'Business Insight')], max_length=20)),
                ('input_data', models.JSONField()),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'AI Analyses',
                'db_table': 'ai_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='ID of the user or student')),
                ('user_email', models.EmailField(help_text='Email of the user', max_length=254)),
                ('user_role', models.CharField(help_text='Role: STUDENT, LIBRARY, etc.', max_length=20)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_chat_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
